### ISSUE TITLE
Unittests broken

### ISSUE THREAD

**Issue by gselzer** [Labelings/Labeling#13]
Half of the `unittest` tests break on my machine. We should really fix them.

**Comment by tomburke-rse** [comment]
On it. I  am currently switching to pytest and fix them while I'm doing it.

**Comment by gselzer** [comment]
Sounds good.

Can we also ensure that the tests pass before merging?

If you'd like, I can set up GitHub Actions for this project.

**Comment by tomburke-rse** [comment]
I just added the already available workflow for build and test. I'll do the other (pypi and conda) after

**Comment by tomburke-rse** [comment]
Unitests working now, switch to pytest is done and the github action also works.
