### ISSUE TITLE
Pillow<10 dependency prevents compatibility with Python 3.12+

### ISSUE THREAD

**Issue by ctrueden** [Labelings/Labeling#17]
Pillow is now on version 10.3.0, which includes support for Python 3.12.

From imagej/pyimagej#306
> [Labeling] relies on pillow<10. This constrains installation to Pillow v9.5, which prevents compatibility with Python 3.12 as well as with other popular image handling libraries such as imageio, that also depend on Pillow.

@jdeschamps Would you have time to make a new release of this project with the dependencies fixed, so that PyImageJ can work with 3.12? Or do you think we should go with @BptGrm's idea of forking the Labeling code into pyimagej itself?

**Comment by jdeschamps** [comment]
Hi @ctrueden

We will look into it next week!

**Comment by jdeschamps** [comment]
Yes, I don't see any reason to constrain the dependencies here.

I relaxed them: https://github.com/Labelings/Labeling/commit/d160bc685199e44cf3bb52e27878ff718c71b2a9

**Comment by jdeschamps** [comment]
[v0.1.14 released](https://pypi.org/project/labeling/) 🎉

**Comment by ctrueden** [comment]
Ah yes, the duplicate dependency management between conda-forge recipes and the project itself. Fun stuff. I filed conda-forge/labeling-feedstock#6 to hopefully help with this.

**Comment by elevans** [comment]
Doh :facepalm:! I should have done that. Thanks for filing that PR Curtis :).

**Comment by elevans** [comment]
This issue can be safely closed now with version `0.1.14` on `conda-forge`.
